import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white shadow-sm border-b">
          <div className="container mx-auto px-4">
            <div className="flex justify-between items-center h-16">
              <Link href="/" className="text-xl font-bold text-gray-800">
                Al-Badar
              </Link>
              <div className="flex space-x-6">
                <Link href="/" className="text-gray-600 hover:text-gray-900">
                  Home
                </Link>
                <Link href="/visi-misi" className="text-gray-600 hover:text-gray-900">
                  Visi & Misi
                </Link>
                <Link href="/post" className="text-gray-600 hover:text-gray-900">
                  Blog
                </Link>
                <Link href="/sejarah" className="text-gray-600 hover:text-gray-900">
                  Sejarah
                </Link>
                <Link href="/kegiatan" className="text-gray-600 hover:text-gray-900">
                  Kegiatan
                </Link>
                <Link href="/informasi-psb" className="text-gray-600 hover:text-gray-900">
                  PSB
                </Link>
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
